### ISSUE TITLE
Might be helpful to require rich version a bit more loosely

### ISSUE THREAD

**Issue by tombola** [kylepollina/objexplore#21]
In no way a real blocker - especially as objexplore used primarily/solely in a local dev environment.

 Rich has become really popular, and I use it in a lot of my own code, especially in django management commands. I then choose to use objexplore sometimes in debugging.

It would be helpful for me if objexplore defined a range of (prior) rich releases that were compatible (if that were possible), so that the (pinned) rich requirement in my app was not so likely to conflict.

Not a big deal, just means I may sometimes have to reinstall objexplore to use it, as subsequent installs of my apps requirements.txt will have defined a different version of rich, and required me to uninstall objexplore if it conflicts.

If this makes testing/maintenance/development difficult please ignore/close, happy to install when I need/want it.

**Comment by kylepollina** [comment]
Yeah that's not a bad idea, I'll set the version >= 10.9.0 because that is where it has been since I started this project
