### ISSUE TITLE
QUESTION. Have you tried urwid?

### ISSUE THREAD

**Issue by 4l1fe** [kylepollina/objexplore#24]
Hey. I see that you use **blessed** with **rich** for the util. Did you look at **urwid** and if yes why you chose the first?

I'm working on a simple tui util and am not that **urwid** is the right way to go to as it's not very clear in its documentation. Urwid looks mature, but complicated. At the same time, it provides good functonality and abstractions for resizing, overlaying, combining and etc.

**Comment by kylepollina** [comment]
The reason I did not use urwid was because it was complicated to use and the documentation hasn't been updated in some time.

**Comment by 4l1fe** [comment]
Yeah, i think the same. And may i know your opinion about blessed? Isn't it too low-level?

I've tried blessed in a basic scenario and didn't find a way for printing stream data.

**Comment by kylepollina** [comment]
I like the blessed package - I would make sure to use the fork here: https://github.com/jquast/blessed - this is the maintained version and is much more consistently updated.

**Comment by kylepollina** [comment]
I'm not sure how to use it to print streamed data, but I bet there's a way to use it in a while True loop and continuously read from stdin

**Comment by 4l1fe** [comment]
Thank you for sharing, appreciate it!
