### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by RhetTbull** [kylepollina/objexplore#5]
**Is your feature request related to a problem? Please describe.**
No license is specified which will prevent some authors (including me) from using objexplore in our own code.

**Describe the solution you'd like**
Include a permissive open source license.  My preference is [MIT License](https://opensource.org/licenses/MIT) which is the same license [rich uses](https://github.com/willmcgugan/rich/blob/master/LICENSE) (which is used in objexplore).

**Describe alternatives you've considered**
N/A -- code without a license is a potential legal liability for any project.

**Additional context**
N/A

**Comment by kylepollina** [comment]
Good idea!! Added a MIT license to the project. Thanks!

**Comment by RhetTbull** [comment]
Thanks!
