### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGWINCH'

### ISSUE THREAD

**Issue by DataScienceResearcher** [kylepollina/objexplore#6]
**I attempted to use the basic code in the tutorial:**

"""
from objexplore import explore
import pandas
explore(pandas)
"""

**And received the following error:**

╭──────────────────────────── Traceback (most recent call last) ────────────────────────────╮
│ C:\ProgramData\Anaconda3\envs\Fast_AI\lib\site-packages\objexplore\objexplore.py:334 in   │
│ explore                                                                                   │
│                                                                                           │
│   331 def explore(obj: Any) -> Any:                                                       │
│   332 │   """ Run the explorer on the given object """                                    │
│   333 │   try:                                                                            │
│ ❱ 334 │   │   e = Explorer(obj)                                                           │
│   335 │   │   return e.explore()                                                          │
│   336 │   except Exception as e:                                                          │
│   337 │   │   console.print_exception(show_locals=True)                                   │
│                                                                                           │
│ ╭─────────────────────────────────────── locals ────────────────────────────────────────╮ │
│ │   e = AttributeError("module 'signal' has no attribute 'SIGWINCH'")                   │ │
│ │ obj = <module 'numpy' from                                                            │ │
│ │       'C:\\ProgramData\\Anaconda3\\envs\\Fast_AI\\lib\\site-packages\\numpy\\__init_… │ │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                           │
│ C:\ProgramData\Anaconda3\envs\Fast_AI\lib\site-packages\objexplore\objexplore.py:57 in    │
│ __init__                                                                                  │
│                                                                                           │
│    54 │   │   )                                                                           │
│    55 │   │                                                                               │
│    56 │   │   # Run self.draw() whenever the win change signal is caught                  │
│ ❱  57 │   │   signal.signal(signal.SIGWINCH, self.draw)                                   │
│    58 │                                                                                   │
│    59 │   def explore(self) -> Optional[Any]:                                             │
│    60 │   │   """ Open the interactive explorer """                                       │
│                                                                                           │
│ ╭─────────────────────────────────────── locals ────────────────────────────────────────╮ │
│ │ cached_obj = <objexplore.cached_object.CachedObject object at 0x000002B7BF0595E0>     │ │
│ │        obj = <module 'numpy' from                                                     │ │
│ │              'C:\\ProgramData\\Anaconda3\\envs\\Fast_AI\\lib\\site-packages\\numpy\\… │ │
│ │       self = <objexplore.objexplore.Explorer object at 0x000002B7BF0593D0>            │ │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯ │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'signal' has no attribute 'SIGWINCH'

**I also tried to use explore(numpy) and received the same error.**

**Comment by kylepollina** [comment]
Ah. Looks like SIGWINCH doesn't work on windows. I'll add a patch to check for the operating system. The only problem is the terminal will not auto redraw when the terminal size changes. I will open a PR for this

**Comment by kylepollina** [comment]
Issue has been fixed, reinstall the latest version with `pip install objexplore --upgrade` and see if the issue persists
